apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dms-python
  namespace: nbe-dms
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/websocket-services: "dms-python"
spec:
  ingressClassName: nginx
  rules:
    - host: dms.nbe.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dms-python
                port: {number: 8000}
