apiVersion: v1
kind: Secret
metadata:
  name: dms-python-secrets
  namespace: nbe-dms
type: Opaque
stringData:
  API_KEY: "change-me-in-prod"
  JWT_SECRET: "change-me-in-prod"
  DATABASE_URL: "postgresql+psycopg://dms:dms@postgres:5432/dms"
