apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nbe-dms.fullname" . }}-secrets
  labels: {{- include "nbe-dms.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: "{{ $v }}"
  {{- end }}
